### ISSUE TITLE
305 - XXX | Unknown error: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by ducquoa** [protonmeacc/Not-Pixel-bot#2]
what does this mean? it only happens to this account, my other 4 works fine. I don't seem to see any difference on my accounts

**Comment by protonmeacc** [comment]
> what does this mean? it only happens to this account, my other 4 works fine. I don't seem to see any difference on my accounts

Most likely, you have small values ​​specified in your config. For example: MAX_PAINT_LEVEL on your account is leveled at level 5. And in the config file there is MAX_PAINT_LEVEL: int = 3.

**Comment by ducquoa** [comment]
problem solved, thank you.

**Comment by ducquoa** [comment]
Issue solved. Thank you.
